### ISSUE TITLE
Cloning with git-fallback-clone seems to fail

### ISSUE THREAD

**Issue by GDWBaer** [ckotzbauer/sbom-operator#179] opened 2022-09-20 10:11 UTC
Hi @ckotzbauer. Thank you very much for your work trying to support Azure DevOps repos.
Unfortunately it seems to be not working for me.
This is the log output from a sbom-operator pod deployed into kubernetes:

```time="2022-09-20T09:11:41Z" level=info msg="Version: 0.17.0"
time="2022-09-20T09:11:41Z" level=info msg="Commit: 0f4635d8a13131aa655e6096beb6f46a92199ce9"
time="2022-09-20T09:11:41Z" level=info msg="Built at: 2022-09-17T08:59:11Z"
time="2022-09-20T09:11:41Z" level=info msg="Built by: goreleaser"
time="2022-09-20T09:11:41Z" level=info msg="Go Version: go1.19"
time="2022-09-20T09:11:41Z" level=debug msg="Targets set to: [git]"
time="2022-09-20T09:11:41Z" level=info msg="Webserver is running at port 8080"
time="2022-09-20T09:11:41Z" level=info msg="Wait for cache to be synced"
time="2022-09-20T09:11:41Z" level=error msg="Open or clone failed" error="'git clone -b sbom-operator https://******@dev.azure.com/******/**********/_git/******************* /work/sbom' failed: Cloning 
into '/work/sbom'..."
time="2022-09-20T09:11:41Z" level=info msg="Start pod-informer"
time="2022-09-20T09:11:41Z" level=info msg="Processing image ghcr.io/ckotzbauer/sbom-operator@sha256:846b4d38b700d4c995404ff038f97b1748e3018e234b1255d7989a8ed7647a2e"
time="2022-09-20T09:11:41Z" level=info msg="Finished cache sync"
time="2022-09-20T09:11:41Z" level=error msg="An error occurred while processing /work/sbom/aks/sbom" error="lstat /work/sbom/aks/sbom: permission denied"
time="2022-09-20T09:11:41Z" level=debug msg="Pod sbom-operator/sbom-operator-788b8f6697-7k59x needs to be analyzed"
time="2022-09-20T09:11:41Z" level=debug msg="Skip image ghcr.io/ckotzbauer/sbom-operator@sha256:846b4d38b700d4c995404ff038f97b1748e3018e234b1255d7989a8ed7647a2e"
time="2022-09-20T09:11:41Z" level=error msg="An error occurred while processing /work/sbom/aks/sbom" error="lstat /work/sbom/aks/sbom: permission denied"
time="2022-09-20T09:11:44Z" level=error msg="Directory could not be created" error="mkdir /work/sbom/aks: permission denied"
time="2022-09-20T09:12:16Z" level=info msg="Processing image registry.k8s.io/ingress-nginx/kube-webhook-certgen@sha256:549e71a6ca248c5abd51cdb73dbc3083df62cf92ed5e6147c780e30f7e007a47"
time="2022-09-20T09:12:18Z" level=error msg="Directory could not be created" error="mkdir /work/sbom/aks: permission denied"
time="2022-09-20T09:12:18Z" level=debug msg="Image registry.k8s.io/ingress-nginx/kube-webhook-certgen@sha256:549e71a6ca248c5abd51cdb73dbc3083df62cf92ed5e6147c780e30f7e007a47 marked for removal"
time="2022-09-20T09:12:18Z" level=debug msg="Start to remove old SBOMs"
time="2022-09-20T09:12:18Z" level=error msg="Open failed" error="stat /work/sbom/.git: permission denied"
time="2022-09-20T09:12:18Z" level=debug msg="Deleted old SBOM: /work/sbom/aks/sbom/registry.k8s.io/ingress-nginx/kube-webhook-certgen/sha256_549e71a6ca248c5abd51cdb73dbc3083df62cf92ed5e6147c780e30f7e007a47/sbom.json"
```

Could it be that the plain git clone return is seen as an error by the wrapper code? Just guessing since it is saying 'Cloning into ...' as if it worked.

**Comment by ckotzbauer** [comment] 2022-09-20 11:22
Hi @GDWBaer,
can you please share your config (helm-chart values or deployment.yaml) that I can see the parameter you added?

**Comment by GDWBaer** [comment] 2022-09-23 08:19
Sorry for replying late. I overlooked the info mail. My values.yaml file looks like:
`image:
  tag: "0.17.0"

args:
  targets: git
  format: cyclonedxjson
  git-author-email: peter.niermann@weidmueller.com
  git-author-name: "Peter Niermann"
  git-repository: https://******@dev.azure.com/******/**************/_git/*************************
  git-branch: "sbom-operator"
  git-path: aks/sbom
  git-fallback-clone:
  git-workingtree: /work/sbom
  #git-username: "***********"
  #git-password: "****************************************************"
  git-access-token: "****************************************************"
  verbosity: debug

#envVars:
#  - name: SBOM_GIT_ACCESS_TOKEN
#    valueFrom:
#      secretKeyRef:
#        name: "sbom-operator"
#        key: "accessToken"`

I played around with setting the access token by parameter and from kubernetes secret...

**Comment by GDWBaer** [comment] 2022-09-23 08:22
Maybe an image is easier to read here:
![grafik](https://user-images.githubusercontent.com/6882308/191920052-963edd87-6323-4ffe-a0df-eab4673c2b05.png)

**Comment by ckotzbauer** [comment] 2022-09-23 08:23
Thanks, I will have a look at this on the weekend

**Comment by ckotzbauer** [comment] 2022-09-24 16:27
I could reproduce the issue: The problem was, that the repo or branch was empty. The operator assumes a fully initialized repository/branch to work on. There's no logic which creates the specified branch if it does not exist. Please commit a README or something else to the branch. I will add this requirement to the docs.

Feel free to reply here, if this doesn't work.

**Comment by GDWBaer** [comment] 2022-09-28 07:58
Hi Christian, the branch is definitely existing in the origin. Do you see a way of getting the complete error message git is throwing? It seems to be only a stub (1st line?) for me:
`time="2022-09-28T07:45:05Z" level=error msg="Open or clone failed" error="'git clone -b sbomtest https://dev.azure.com/******/*****************/_git/******************** /work' failed: Cloning into '/work'..."`
When I log into the container I can successfully clone the repo to an empty destination:
![grafik](https://user-images.githubusercontent.com/6882308/192722255-5dd2ab8a-cb55-4856-a5b1-33612523964a.png)
The original destination is not empty anymore because the sbom-operator starts to create sboms even after the clone failed.

**Comment by ckotzbauer** [comment] 2022-10-01 15:23
I added the exit-code from the git-command to the error-message in the newest release. The stderr message from the command is logged, so it seems that git doesn't emit an error-message. @GDWBaer

**Comment by acook8** [comment] 2022-11-08 17:54
@GDWBaer I was having the same issue with Azure DevOps. What I did to get it to work was set SBOM_GIT_REPOSITORY to https://<pat>@dev.azure.com/<organization>/<project>/_git/<repo>

**Comment by GDWBaer** [comment] 2022-11-09 07:55
> @GDWBaer I was having the same issue with Azure DevOps. What I did to get it to work was set SBOM_GIT_REPOSITORY to https://{pat}@dev.azure.com/{organization}/{project}/_git/{repo}

Hi, thanks for the hint. Could you give a more complete example? Is this env var the only config you used? Is the {pat} raw or base64 encoded? I tried with a raw token without luck, yet.

**Comment by acook8** [comment] 2022-11-10 18:45
> Hi, thanks for the hint. Could you give a more complete example? Is this env var the only config you used? Is the {pat} raw or base64 encoded? I tried with a raw token without luck, yet.

The PAT I used was not encoded. The arguments I have set are:
* git-author-email
* git-author-name
* git-username
* git-path
* git-fallback-clone

And I have these environment variables:
* SBOM_GIT_PASSWORD
* SBOM_GIT_REPOSITORY

I probably don't need all of those set, but I haven't gone back and cleaned up anything that isn't needed

**Comment by ckotzbauer** [comment] 2022-12-04 14:19
Hey @acook8, @GDWBaer,
I just pushed `ghcr.io/ckotzbauer/sbom-operator:0.23.0-beta.1` (hopefully 0.23.0 later today) with go-git 5.5.0 built-in. This release added support for `multi_ack`. I justed tested a private Azure DevOps repo with this release without the `--git-fallback-clone` flag and it worked. Could you please have a look and give me a quick hint if this works for you?
If yes, I will remove the fallback-clone in the near future.

I tested with this URL-format and username and password (as flags): https://{organization}@dev.azure.com/{organization}/{project}/_git/{repo}

**Comment by ckotzbauer** [comment] 2023-01-22 15:33
Closing this for now. Please respond if there are still errors.

**Closed by ckotzbauer** 2023-01-22 15:33 UTC
Labels: kind/bug
